services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chefai-backend
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    